### ISSUE TITLE
Problem on DS hardware

### ISSUE THREAD

**Issue by d8omoc80y** [eCDP-English/translation#46]
The patch and original save file work completely fine on my emulator (I use MelonDS). However, I have a DSi XL, and I have used the exact patched .nds and original save file on my DSi, and the translations work, however, when I attempt to enter my password, I am met with an error saying "Enter the serial code when loading the game for the first time." I have imported 2 save files, (the original and the save file created automatically on MelonDS) and neither of them work. Please help so people can run the translations on DS hardware. 

![WIN_20240213_16_24_04_Pro](https://github.com/eCDP-English/translation/assets/159964206/2d445b75-fc97-4a80-8524-574752f52f34)
![WIN_20240213_16_24_01_Pro](https://github.com/eCDP-English/translation/assets/159964206/3fb16242-5dc0-4c16-932a-79f6e2805f0a)

**Comment by SirenGlitch** [comment]
111111
111111
0QKDE9
111111
111111

It's not a problem with the translation, it's either the save file name, or that it the save won't work on your hardware. Either way, just enter the above for the serial code thing. After launching on the second time, you can just enter the password as 111111 on both prompts. From there, you can use manager mode to add a new worker with any ID you want (482500 is the one from the "original" save file, as you called it.) Then relaunch the game, change password, enter the newly added worker ID, 000000 for the current password (this is the default for a new worker), then whatever you want for the new password (again, 482500 is the one from the "original" save file). Any problems, just do @SirenGlitch to ping me and I'll try and help

**Comment by d8omoc80y** [comment]
THANK YOU SO MUCH DUDE i really appreciate you answering quickly,, it works perfectly now :) i cant thank you enough!!

**Comment by d8omoc80y** [comment]
THANK YOU SO MUCH DUDE i really appreciate you answering quickly,, it works perfectly now :) i cant thank you enough!!
