### ISSUE TITLE
[REQUEST] Add support for accented characters

### ISSUE THREAD

**Issue by Shokaiii** [eCDP-English/translation#47]
I'm using your project and translating from English to Portuguese, but Portuguese uses a lot of accented characters (like ç, á, à, â, ã, é, ê, ô, õ, ó, ú) and they cause an error when making the patch.

Would it be possible to add support for these characters in the script?

I'm already trying to edit the game's font so that the characters appear ingame.

Thank you for everything <3

**Comment by SirenGlitch** [comment]
It would definitely be possible, I need to fork it myself as this repo seems EOL. I'll try and add it when I get to my dev machine

**Comment by Shokaiii** [comment]
@SirenGlitch thank you so much <3 you're a savior

**Comment by SirenGlitch** [comment]
> @SirenGlitch thank you so much <3 you're a savior

Thought I'd mention, I've just made the fork at [SirenGlitch/eCDP-English](https://github.com/SirenGlitch/eCDP-English) and am about to start taking a look at the code

**Comment by SirenGlitch** [comment]
Note: repo doesn't exist yet, just changing a few things and it'll be up

**Comment by KabanFriends** [comment]
As far as I'm aware, the Shift-JIS encoding used by the game to store strings does not have the mapping for accented characters, so if anyone is interested in supporting them, you will need to replace existing characters

**Comment by SirenGlitch** [comment]
> As far as I'm aware, the Shift-JIS encoding used by the game to store strings does not have the mapping for accented characters, so if anyone is interested in supporting them, you will need to replace existing characters

Probably at least worth the try? I have a repo and dev environment so I just need the time and docs...
