### ISSUE TITLE
Password/ fresh rom

### ISSUE THREAD

**Issue by projectfaded** [eCDP-English/translation#48]
I don't know what the Serial number of this game

**Comment by SirenGlitch** [comment]
Do you mind explaining further? Are you trying to set a password on the base ROM without the save file?

**Comment by SirenGlitch** [comment]
If so, I'm gonna leave the link to an [Older comment of mine](https://github.com/eCDP-English/translation/issues/46#issuecomment-1942746348) explaining what to do

**Comment by KabanFriends** [comment]
This is unrelated with the translation project, closing the issue
